// app/(payload)/admin/importMap.ts
// This file maps custom admin components for Payload.
// It's auto-generated by Payload during build, but we need a minimal version for dev.

export const importMap = {}
